# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GpxParserTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CoreGPX'
  # Pods for GpxParserTest

  target 'GpxParserTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GpxParserTestUITests' do
    # Pods for testing
  end

end
