# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TODOAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for TODOAPP
 
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
 
 # Optionally, include the Swift extensions if you're using Swift.
 #pod 'FirebaseFirestoreSwift'
end
