# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ColorfulBall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

  # Pods for ColorfulBall

end
