# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPXMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CoreGPX'
  # Pods for GPXMaker

  target 'GPXMakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPXMakerUITests' do
    # Pods for testing
  end

end
